language: node_js
node_js:
  - 12.16.3
dist: trusty
sudo: false

addons:
  ssh_known_hosts:
    - 45.79.35.9

before_install:
  - openssl aes-256-cbc -K $encrypted_08fd58b20b48_key -iv $encrypted_08fd58b20b48_iv -in example-travis.enc -out example-travis -d
    - eval "$(ssh-agent -s)"
    - cp scripts/example-travis ~/.ssh/example-travis
    - chmod 600 ~/.ssh/example-travis
    - ssh-add ~/.ssh/example-travis
    - echo -e "Host 45.79.35.9\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
